# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-24 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='votes',
        ),
        migrations.AddField(
            model_name='feature',
            name='totalDonation',
            field=models.IntegerField(default=0),
        ),
    ]
