# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-20 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
