# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bug_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'In progress'), ('completed', 'Completed')], default='pending', max_length=12),
        ),
    ]
