# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-21 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20190921_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='views',
            new_name='comments',
        ),
    ]
